### ISSUE TITLE
Split loaded data into 'from' + 'to' sequence

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/ist-664#21]
We need to split our loaded data into a `from` and `to` sequence.

**Comment by jeff1evesque** [comment]
The following attributes will need to further investigation to determine the `from` and `to` connection:

- `id`
- `link_id`
- `parent_id`

Then, we'll need  to decide whether to set a minimum filter on the following attributes:

- `score`
- `ups`

By setting a minimum filter, we can ensure that only popular + relevant reddit threads are used for train.

**Comment by jeff1evesque** [comment]
Some rows share identical `link_id`, and `parent_id`, and between other row(sS. However, there are cases where the `link_id`, and `parent_id` are not the same in a given row, while the former `link_id` is identical to the value of another row(s) `link_id`.

**Comment by jeff1evesque** [comment]
The `parent_id` value `aaa_xxx` corresponds to the `id` (parent) value `xxx`, where `aaa` represents the `kind` of post.  Therefore, we can develop an association:

- parse the `id` value `xxx` from the `parent_id`
  - the `body` content associated with the original `parent_id` is assigned the `from` value
  - the `body` content associated with the `id` value `xxx` is assigned the `to` value

**Comment by jeff1evesque** [comment]
We need to fix our reducer function in our `app/select.py`:

```bash
root@ubuntu-xenial:/home/vagrant/ist-xxx# python3 train.py
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    pairs = select(client, database, collection)
  File "/home/vagrant/ist-664/app/select.py", line 60, in select
    return col.map_reduce(map, reduce, 'to_from')
  File "/usr/local/lib/python3.5/dist-packages/pymongo/collection.py", line 2751, in map_reduce
    collation=collation, session=session)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/collection.py", line 244, in _command
    retryable_write=retryable_write)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: exception: TypeError: Cannot call method 'split' of null near 'parent_id.split('_',1)[1];    for(var j ='
root@ubuntu-xenial:/home/vagrant/ist-xxx#
```

**Comment by jeff1evesque** [comment]
If we implement our current `app/select.py`, with adjustments to the reducer:

```python
    #
    # @to (key), the parent comment
    # @from (value), reply to parent comment
    #
    reduce = Code(
        "function (key, values) {"
        "  var results = {'to': [], 'from': []};"
        "  for (var i = 0; i < values.length; i++) {"
        "    wantedKey = 'parent_id';"
        "    wantedVal = values[i].parent_id.split('_',1)[1];"
        "    for(var j = 0; j < values.length; j++) {"
        "      if ("
        "        values[j].hasOwnProperty(wantedKey) &&"
        "        values[j][wantedKey] === wantedVal &&"
        "        values[j].body != values[i].body"
        "      ) {"
        "        results.to.push(values[j].body);"
        "        results.from.push(values[i].body);"
        "      }"
        "    }"
        "  }"
        "  return {"
        "    'id': 'jeff',"
        "    'parent_id': values[0].parent_id,"
        "    'body': values[0].body,"
        "  }"
        "}"
    )

    # select data
    return col.map_reduce(map, reduce, 'to_from')
```

Then, running our `select.py`, reduced on the first element in the `values` array:

```bash
root@ubuntu-xenial:/home/vagrant/ist-xxx# python3 train.py
{'_id': 'jeffbob', 'value': {'parent_id': 't3_15xh', 'id': 'jeff', 'body': 'THAN the title suggests.  Whoops.'}}
```

**Comment by jeff1evesque** [comment]
Adjusting the reducer in the our `app/select.py`:

```python
...
    reduce = Code(
        "function (key, values) {"
        "  var results = {'to': [], 'from': []};"
        "  for (var i = 0; i < values.length; i++) {"
        "    wantedKey = 'parent_id';"
        "    wantedVal = values[i].parent_id.split('_')[1];"
        "    for(var j = 0; j < values.length; j++) {"
        "      if ("
        "        values[j].hasOwnProperty(wantedKey) &&"
        "        values[j][wantedKey] === wantedVal &&"
        "        values[j].body != values[i].body"
        "      ) {"
        "        results.to.push(values[j].body);"
        "        results.from.push(values[i].body);"
        "      }"
        "    }"
        "  }"
        "  return {"
        "    'id': values[0].id,"
        "    'parent_id': values[0].parent_id,"
        "    'parent_split': values[0].parent_id.split('_')[1],"
        "  }"
        "}"
    )

    # select data
    return col.map_reduce(map, reduce, 'to_from')
```

Shows that the `split` is functional:

```bash
root@ubuntu-xenial:/home/vagrant/ist-xxx# python3 train.py
{'_id': 'jeffbob', 'value': {'parent_split': '15xh', 'parent_id': 't3_15xh', 'id': 'c166b'}}
```
